# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190319_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
